SET ansi_warnings OFF
SET IDENTITY_INSERT [dbo].[News] ON;

MERGE [dbo].[News] U
USING (VALUES
	(1, 'Ronaldo scores hat-trick in Madrid derby', 'Cristiano Ronaldo is 39th career hat-trick gave Real Madrid a derby win over city rivals Atletico to increase their lead at the top of La Liga.', NULL, 1,'2b0ed59e-570c-42ba-8d83-b140c52c4cc8', '2016-03-03 7:29:29 AM'),
	(2, 'Andy Murray v Novak Djokovic', 'Andy Murray will face Novak Djokovic with the ATP World Tour Finals title and year-end number one ranking at stake on Sunday.', NULL, 2, '2b0ed59e-570c-42ba-8d83-b140c52c4cc8', '2016-03-03 7:29:29 AM'),
	(3, 'Wayne Rooney', 'Wayne Rooney claims he suffered disgraceful treatment on England duty',  NULL, 3, '2b0ed59e-570c-42ba-8d83-b140c52c4cc8', '2016-03-03 7:29:29 AM'),
	(4, 'England forwards coach Steve Borthwick set to join 2017 Lions set-up', 'England forwards coach Steve Borthwick looks set to join the British and Irish Lions coaching team for next year tour of New Zealand.',  NULL, 4, '2b0ed59e-570c-42ba-8d83-b140c52c4cc8', '2016-03-03 7:29:29 AM'),
	(5, 'Amethyst goes Dark on Soi LK Metro', 'Amethyst Club A-GoGo re-opened on Soi LK Metro on 3rd November but has already gone dark. It was reported dark on the 15th and 16th of November.', NULL, 5, '2b0ed59e-570c-42ba-8d83-b140c52c4cc8', '2016-03-03 7:29:29 AM'),
	(6, ' Miss B Haven...', 'A new bar has opened on Soi 6 named Miss B Haven. It opened on the 11th November and is located mid soi on the north side, next door to Chilli Bar', NULL, 6, '2b0ed59e-570c-42ba-8d83-b140c52c4cc8', '2016-03-03 7:29:29 AM'),
	(7, ' Normal service resuming...', 'Lita Bar , the ladyboy bar that had closed on Soi BJ off Walking Street, has reopened on Soi Post Office (Soi 13/2).', NULL, 7, '2b0ed59e-570c-42ba-8d83-b140c52c4cc8', '2016-03-03 7:29:29 AM'),
	(8, 'Passion for sale...', 'On Soi Diamond the previous location of The Sea gogo has become Diamond Sports Bar, which is always deserted when I walk past.', NULL, 8, '2b0ed59e-570c-42ba-8d83-b140c52c4cc8', '2016-03-03 7:29:29 AM'),
	(9, 'Jeanette Winterson: my family Christmas', 'In an extract from her new book Christmas Days, Jeanette Winterson shares her childhood memories and favourite seasonal recipes, including Mum’s mince pies and Dads sherry trifle', NULL, 9, '2b0ed59e-570c-42ba-8d83-b140c52c4cc8', '2016-03-03 7:29:29 AM'),
 	(10, 'How I made Wendy the real star of Peter Pan', 'The director Sally Cookson is renowned for turning family shows upside down. As her National Theatre Peter Pan opens, she talks GoogleId why she made Wendy the real star of the show', NULL, 10, '2b0ed59e-570c-42ba-8d83-b140c52c4cc8', '2016-03-03 7:29:29 AM'),
	(11, 'When wills go bad: ‘It was the cruellest thing you could imagine’', 'The mother who left all her money to animals rather than her daughter. The man forced to read out a catalogue of his father failings. Wills can leave emotional scars', NULL, 11, '2b0ed59e-570c-42ba-8d83-b140c52c4cc8', '2016-03-03 7:29:29 AM'),
	(12, '7 things to do if you don’t like your children’s friends', 'Be honest with yourself GoogleId why you dislike them, try to befriend them. And never let your child know you feel that way', NULL, 12, '2b0ed59e-570c-42ba-8d83-b140c52c4cc8', '2016-03-03 7:29:29 AM'),
	(13,  'Who could be in Trump Cabinet?', 'President-elect Trump will have GoogleId 400 government positions to fill, including some of the most important posts in the US government. His team has been at work coming up with possible candidates for the top jobs, but there is a smaller universe of Republicans who were close to his campaign. Much of the Washington establishment kept him at arms length. Others, including some former GOP cabinet secretaries, rejected him entirely.', NULL, 13, '2b0ed59e-570c-42ba-8d83-b140c52c4cc8', '2016-03-03 7:29:29 AM'),
	(14, 'Michael Flynn ran company that lobbied for foreign clients while he received intel briefings', 'Washington (CNN)Retired Army Lt. Gen. Michael Flynn, President-elect Donald Trump preferred choice for National Security Adviser, was running a company that was lobbying on behalf of foreign clients even as he was receiving classified intelligence briefings during the campaign.', NULL, 14, '2b0ed59e-570c-42ba-8d83-b140c52c4cc8', '2016-03-03 7:29:29 AM'),
	(15, 'Freshman Van Hollen takes over Dems Senate campaign arm', '"He has the confidence of our caucus and will do a great job for our candidates running in 2018. The map is tough for Democrats, but I have no doubt that Senator-elect Van Hollen is up to the task," said Senate Minority Leader Chuck Schumer, himself the new head of the Senate Democrats.', NULL, 15, '2b0ed59e-570c-42ba-8d83-b140c52c4cc8', '2016-03-03 7:29:29 AM'),
	(16, 'Japan Abe on US mission to "build trust" with Donald Trump', 'Japanese Prime Minister Shinzo Abe said Thursday he had a "very candid discussion" with President-elect Donald Trump, during a brief press availability following their in-person meeting.', NULL, 16, '2b0ed59e-570c-42ba-8d83-b140c52c4cc8', '2016-03-03 7:29:29 AM'),
	(17, 'Doctors see surge in men seeking surgery-free double chin solution', 'Even though Scott Kaiser had a healthy diet and stayed active with regular cardio and weight lifting, he realized he was developing a double chin, something that also seemed to plague other men in his family.', NULL, 17, '2b0ed59e-570c-42ba-8d83-b140c52c4cc8', '2016-03-03 7:29:29 AM'),
	(18, 'Trump Apprentice alum Leeza Gibbons on the importance of caregiving', 'Leeza Gibbons may be best known for her co-hosting role on “Entertainment Tonight” or for winning “The Apprentice” in the final season that Donald Trump hosted, but now, she is making name for herself in the medical space by raising awareness for caregivers.', NULL, 18, '2b0ed59e-570c-42ba-8d83-b140c52c4cc8', '2016-03-03 7:29:29 AM'),
	(19, 'Reliance on food pantries can make healthy eating difficult', 'People who rely on food pantries for their meals may not receive enough dairy, fruits or vegetables to get all the nutrients they need for a healthy diet, two recent studies suggest.', NULL, 19, '2b0ed59e-570c-42ba-8d83-b140c52c4cc8', '2016-03-03 7:29:29 AM'),
	(20, 'Moderate drinking may have some heart benefits', 'NEW ORLEANS — Moderate drinking may have positive effects on some aspects of heart health beyond those seen with light drinking, a new study from Australia finds. The people in the study who drank 10 to 20 grams of alcohol per day were less likely to develop a condition called metabolic syndrome, which is linked with heart disease, compared with the people who drank less than 10 g of alcohol per day. In the U.S., a standard drink contains GoogleId 14 g of alcohol, according to the National Institute on Alcohol Abuse and Alcoholism.', NULL, 20, '2b0ed59e-570c-42ba-8d83-b140c52c4cc8', '2016-03-03 7:29:29 AM'),
	(21, 'Tech Q&A: Running a background check, avoiding cell phone contracts', 'Service providers have begun phasing out contracts, which is a blessing and a curse. On the one hand, there are no strict rules, no automatic renewals, and no elaborate termination steps. Then again, some people have to buy their expensive smartphones outright, where once they were heavily discounted. Until recently, your only options were to pay in advance with companies like T-Mobile or Cricket.', NULL, 21, '2b0ed59e-570c-42ba-8d83-b140c52c4cc8', '2016-03-03 7:29:29 AM'),
	(22, 'Keeping your secrets safe on Amazon, Google, Facebook and Netflix', 'Google often auto-completes your search terms based on personal information, such as your location and previous searches. Anyone looking over your shoulder or borrowing your device might be surprised by the guesses Google makes. Google products that collect your information include Chrome, Google Maps, and YouTube.', NULL, 21, '2b0ed59e-570c-42ba-8d83-b140c52c4cc8', '2016-03-03 7:29:29 AM'),
	(23, 'The hidden costs of new car infotainment systems', 'These days, a new car is basically a computer with wheels. Trunks open automatically. The car parks itself. Rear cameras show you what you can’t see. If you lock your keys inside, you can open the doors by satellite. The flashiest new gadget: a touch screen in the middle of your dashboard. There’s a lot to love GoogleId these infotainment systems. Depending on the brand, you can organize your music, program the GPS and dictate text messages. Console screens are as wide as small tablets and they’re easy to read, even when you’re behind the wheel.', NULL, 21, '2b0ed59e-570c-42ba-8d83-b140c52c4cc8', '2016-03-03 7:29:29 AM'),
	(24, 'How is Wikileaks publishing files even after Assange Internet was cut?', 'Assange has been holed up in the Ecuadorean Embassy in London for five years, but Wikileaks managed on Tuesday to unleash yet another massive dump of Locations hacked from key Hillary Clinton aide John Podesta. Those disclosures came a day after his international hacktivist group said their leader access to the cyber world was severed by the South Ameerican government.', NULL, 21, '2b0ed59e-570c-42ba-8d83-b140c52c4cc8', '2016-03-03 7:29:29 AM'),
	(25, 'Advanced weather satellite rockets into space', 'The most advanced weather satellite ever built rocketed into space Saturday night, part of an $11 billion effort to revolutionize forecasting and save lives.', NULL, 22, '2b0ed59e-570c-42ba-8d83-b140c52c4cc8', '2016-03-03 7:29:29 AM'),
	(26, 'Space station welcomes the oldest woman astronaut, and a bit of Mars', 'The International Space Station gained three new residents Saturday, including the oldest and most experienced woman to orbit the world.', NULL, 22, '2b0ed59e-570c-42ba-8d83-b140c52c4cc8', '2016-03-03 7:29:29 AM'),
	(27, 'Newfound spider species masquerades as a dried-up leaf', 'In the animal kingdom, someCreationTimes the best survival strategy is to pretend to be something you are not — either to ambush unsuspecting prey or to convince predators that you are not very tasty', NULL, 22, '2b0ed59e-570c-42ba-8d83-b140c52c4cc8', '2016-03-03 7:29:29 AM'),
	(28, 'Exploring Mars Ashley Dvorkin speaks with the brains behind the National Geographic miniseries Mars MARS National Geographic Channels MARS explores colonization of the red planet', 'National Geographic Channel’s new event series “MARS” mixes documentary with scripted drama to explore the colonization of Mars in the year 2033.', NULL, 22, '2b0ed59e-570c-42ba-8d83-b140c52c4cc8', '2016-03-03 7:29:29 AM'),
	(29, 'ELMAR HESS AT WHITECONCEPTS, BERLIN', 'Pictures at an Exhibition presents Descriptions of one notable show every weekday ', NULL, 23, '2b0ed59e-570c-42ba-8d83-b140c52c4cc8', '2016-03-03 7:29:29 AM'),
	(30, 'FRANCIS PICABIA, ART-WORLD JAILER: PHILIP PEARLSTEIN ON ‘ONE OF THE PRIME MOVERS OF MODERN ART,’ IN 1970', 'With the Museum of Modern Art in New York preparing to open a much-anticipated Francis Picabia retrospective on Monday, we turn back to the September 1970 issue of ARTnews, in which Philip Pearlstein wrote an essay GoogleId the artist. ', NULL, 24, '2b0ed59e-570c-42ba-8d83-b140c52c4cc8', '2016-03-03 7:29:29 AM'),
	(31, 'DIMITRIS DASKALOPOULOS, NICKOL HACKETT JOIN MCA CHICAGO BOARD OF TRUSTEES', 'The Museum of Contemporary Art, Chicago announced today that Dimitris Daskalopoulos and Nickol Hackett joined its board of trustees on October 31. Daskalopoulos, an ARTnews Top 200 collector, is the founder and member of the board of the Greek investments', NULL, 25, '2b0ed59e-570c-42ba-8d83-b140c52c4cc8', '2016-03-03 7:29:29 AM'),
	(32, 'GRIM PRESIDENTIAL POOL REPORT REFERENCES EDWARD HOPPER, NORMAN MAILER', 'With the President-Elect’s administration filling up with Islamophobes and white nationalists, I’m looking for laughs where I can find them these days. And, bless it, the presidential pool report from Berlin, where President Barack Obama just visited with world leaders.', NULL, 26, '2b0ed59e-570c-42ba-8d83-b140c52c4cc8', '2016-03-03 7:29:29 AM'),
	(33, 'These are the worst airports to travel through during the holidays', 'Passengers trying to fly in and out of JFK, La Guardia and Newark airports for the holidays better buckle up for disappointments.A new study shows that flights involving the three New York City-area airports are more than twice as likely to be canceled than the national average during the Thanksgiving and Christmas holiday season.', NULL, 27, '2b0ed59e-570c-42ba-8d83-b140c52c4cc8', '2016-03-03 7:29:29 AM'),
	(34, 'Terror attacks are changing American holiday travel decisions, survey reports', 'American travelers are changing the international vacation destination map as global terror attacks have altered perceived safety risks, a survey released this week from travel insurance provider Allianz Global Assistance found.', NULL, 28, '2b0ed59e-570c-42ba-8d83-b140c52c4cc8', '2016-03-03 7:29:29 AM'),
	(35, 'Giant, uncut Foxfire diamond goes on display at Smithsonian', 'One of the biggest diamonds ever found is on display at the Smithsonian National Museum of Natural History. The Foxfire diamond is the largest uncut, gem-quality diamond ever mined in North America. It weighs 187 carats, or 1.3 ounces.', NULL, 29, '2b0ed59e-570c-42ba-8d83-b140c52c4cc8', '2016-03-03 7:29:29 AM'),
	(36, 'Elderly man dies on JetBlue flight from Florida to Boston', 'BOSTON –  Authorities say the death of an elderly man on a JetBlue flight from Florida to Boston is not considered suspicious. Massachusetts State Police spokesman David Procopio says the man, whose name was not immediately released, died of apparent natural causes during the flight Thursday from Fort Myers.', NULL, 30, '2b0ed59e-570c-42ba-8d83-b140c52c4cc8', '2016-03-03 7:29:29 AM'))
	
	as S (Id, Heading, Description, Image, Event_Id, Author_Id, Time) 
	ON U.Id = S.Id
	
	WHEN MATCHED AND (
		U.Heading <> S.Heading
		OR U.Description <> S.Description
		OR U.Image <> S.Image
		OR U.Event_Id <> S.Event_Id
		OR U.Author_Id <> S.Author_Id
		OR U.Time <> S.Time) 
	THEN UPDATE SET 
		U.Heading = S.Heading,
		U.Description = S.Description,
		U.Image = S.Image,
		U.Event_Id = S.Event_Id,
		U.Author_Id = S.Author_Id,
		U.Time = S.Time

	WHEN NOT MATCHED BY TARGET
	THEN INSERT (Id, Heading, Description, Image, Event_Id, Author_Id, Time)
		VALUES (S.Id, S.Heading, S.Description, S.Image, S.Event_Id, S.Author_Id, S.Time)
	;
	-- WHEN NOT MATCHED BY SOURCE
	--	THEN DELETE; 
	SET IDENTITY_INSERT [dbo].[News] OFF;